name: bed
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - astropy=5.1
  - asttokens=2.2.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blas=1.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - certifi=2024.2.2
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - comm=0.1.3
  - contourpy=1.0.5
  - cryptography=41.0.3
  - cycler=0.11.0
  - decorator=5.1.1
  - executing=1.2.0
  - fonttools=4.25.0
  - freetype=2.12.1
  - idna=3.4
  - importlib-metadata=6.3.0
  - importlib_metadata=6.3.0
  - importlib_resources=6.1.1
  - ipykernel=5.3.4
  - ipython=8.12.0
  - jedi=0.18.2
  - jpeg=9e
  - jupyter_client=8.1.0
  - jupyter_core=5.3.0
  - kiwisolver=1.4.4
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libdeflate=1.8
  - libexpat=2.5.0
  - libffi=3.3
  - libgcc-ng=12.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=12.2.0
  - libnsl=2.0.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libsodium=1.0.18
  - libstdcxx-ng=12.2.0
  - libtiff=4.4.0
  - libuuid=2.38.1
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - matplotlib-base=3.7.2
  - matplotlib-inline=0.1.6
  - munkres=1.1.4
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openjpeg=2.4.0
  - openssl=1.1.1w
  - packaging=23.0
  - pandas=2.0.3
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.2.0
  - pip=23.0.1
  - platformdirs=3.2.0
  - pooch=1.7.0
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pyerfa=2.0.0
  - pygments=2.15.0
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.8.10
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - pyzmq=25.0.2
  - readline=8.2
  - requests=2.31.0
  - scipy=1.10.1
  - seaborn=0.12.2
  - setuptools=67.6.1
  - six=1.16.0
  - sqlite=3.40.1
  - stack_data=0.6.2
  - tk=8.6.12
  - tornado=6.2
  - traitlets=5.9.0
  - tzdata=2023c
  - urllib3=1.26.18
  - wcwidth=0.2.6
  - wheel=0.40.0
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - aniso8601==9.0.1
      - bayesdesign==0.5.0
      - bs4==0.0.2
      - cobaya==3.5.4
      - corner==2.2.1
      - dill==0.3.8
      - einops==0.6.1
      - fuzzywuzzy==0.18.0
      - getdist==1.5.2
      - mlflow==2.16.0
      - multipledispatch==1.0.0
      - nflows==0.14
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-nccl-cu12==2.20.5
      - portalocker==2.10.1
      - psutil==5.9.8
      - py-bobyqa==1.4.1
      - pyro-ppl==1.8.6
      - speclite==0.20
      - specsim==0.17
      - triton==3.0.0
      - typing-extensions==4.12.2
      - zuko==1.2.0
prefix: /home/ashandonay/miniconda3/envs/bed
