name: new_bed_py311
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - arviz=0.21.0
  - astropy=7.0.0
  - astropy-iers-data=0.2025.6.2.0.38.23
  - asttokens=3.0.0
  - blas=2.131
  - blas-devel=3.9.0
  - bottleneck=1.4.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.4.26
  - certifi=2025.4.26
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.1
  - corner=2.2.3
  - cuda-cccl=12.9.27
  - cuda-cccl_linux-64=12.9.27
  - cuda-command-line-tools=12.1.1
  - cuda-compiler=12.6.2
  - cuda-cudart=12.1.105
  - cuda-cudart-dev=12.1.105
  - cuda-cudart-static=12.9.37
  - cuda-cudart-static_linux-64=12.9.37
  - cuda-cuobjdump=12.9.26
  - cuda-cupti=12.1.105
  - cuda-cuxxfilt=12.9.19
  - cuda-documentation=12.4.127
  - cuda-driver-dev=12.9.37
  - cuda-driver-dev_linux-64=12.9.37
  - cuda-gdb=12.9.19
  - cuda-libraries=12.1.0
  - cuda-libraries-dev=12.6.2
  - cuda-libraries-static=12.9.0
  - cuda-nsight=12.9.19
  - cuda-nvcc=12.4.131
  - cuda-nvdisasm=12.9.19
  - cuda-nvml-dev=12.9.40
  - cuda-nvprof=12.9.19
  - cuda-nvprune=12.9.19
  - cuda-nvrtc=12.1.105
  - cuda-nvrtc-dev=12.1.105
  - cuda-nvrtc-static=12.9.41
  - cuda-nvtx=12.1.105
  - cuda-nvvp=12.9.19
  - cuda-opencl=12.9.19
  - cuda-opencl-dev=12.9.19
  - cuda-profiler-api=12.9.19
  - cuda-runtime=12.1.0
  - cuda-sanitizer-api=12.9.27
  - cuda-toolkit=12.1.0
  - cuda-tools=12.1.1
  - cuda-version=12.9
  - cuda-visual-tools=12.6.2
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - debugpy=1.8.14
  - decorator=5.2.1
  - deprecated=1.2.13
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - expat=2.7.1
  - ffmpeg=4.3
  - filelock=3.17.0
  - fontconfig=2.14.1
  - fonttools=4.58.1
  - freetype=2.13.3
  - fsspec=2025.3.2
  - gds-tools=1.14.0.30
  - getdist=1.6.4
  - giflib=5.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.6.15
  - h5netcdf=1.6.1
  - h5py=3.12.1
  - hdf5=1.14.5
  - icu=73.1
  - idna=3.7
  - importlib-metadata=8.7.0
  - ipykernel=6.29.5
  - ipython=9.3.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - kiwisolver=1.4.8
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libabseil=20250127.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang13=14.0.6
  - libcublas=12.1.0.26
  - libcublas-dev=12.1.0.26
  - libcublas-static=12.9.0.13
  - libcufft=11.0.2.4
  - libcufft-dev=11.0.2.4
  - libcufft-static=11.4.0.6
  - libcufile=1.14.0.30
  - libcufile-dev=1.14.0.30
  - libcufile-static=1.14.0.30
  - libcups=2.4.2
  - libcurand=10.3.10.19
  - libcurand-dev=10.3.10.19
  - libcurand-static=10.3.10.19
  - libcurl=8.12.1
  - libcusolver=11.4.4.55
  - libcusolver-dev=11.4.4.55
  - libcusolver-static=11.7.4.40
  - libcusparse=12.0.2.55
  - libcusparse-dev=12.0.2.55
  - libcusparse-static=12.5.9.5
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.6
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.78.4
  - libgomp=15.1.0
  - libiconv=1.17
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm14=14.0.6
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnghttp2=1.57.0
  - libnpp=12.0.2.50
  - libnpp-dev=12.0.2.50
  - libnpp-static=12.4.0.27
  - libnvfatbin=12.9.19
  - libnvfatbin-dev=12.9.19
  - libnvfatbin-static=12.9.19
  - libnvjitlink=12.1.105
  - libnvjitlink-dev=12.1.105
  - libnvjitlink-static=12.9.41
  - libnvjpeg=12.1.1.14
  - libnvjpeg-dev=12.1.1.14
  - libnvjpeg-static=12.4.0.16
  - libnvvm-samples=12.1.105
  - libopenblas=0.3.29
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=5.29.3
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libtasn1=4.19.0
  - libtiff=4.7.0
  - libtorch=2.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libuv=1.48.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxkbcommon=1.0.3
  - libxml2=2.13.8
  - libxslt=1.1.41
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.7
  - minizip=4.0.3
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munkres=1.1.4
  - mysql=8.4.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nettle=3.7.3
  - networkx=3.4.2
  - nomkl=3.0
  - nsight-compute=2025.2.0.11
  - nspr=4.35
  - nss=3.89.1
  - numexpr=2.10.1
  - numpy=2.0.1
  - numpy-base=2.0.1
  - ocl-icd=2.3.2
  - openblas=0.3.29
  - openblas-devel=0.3.29
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openldap=2.6.4
  - openssl=3.5.0
  - opentelemetry-api=1.34.0
  - opt_einsum=3.4.0
  - pandas=2.2.3
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.1.1
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyerfa=2.0.1.5
  - pygments=2.19.1
  - pyparsing=3.2.3
  - pyro-api=0.1.2
  - pyro-ppl=1.9.1
  - pyside6=6.7.2
  - pysocks=1.7.1
  - python=3.11.13
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pytz=2025.2
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qtbase=6.7.3
  - qtdeclarative=6.7.3
  - qtshadertools=6.7.3
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebengine=6.7.3
  - qtwebsockets=6.7.3
  - readline=8.2
  - requests=2.32.3
  - scipy=1.15.3
  - setuptools=80.9.0
  - six=1.17.0
  - sleef=3.5.1
  - sqlite=3.46.0
  - stack_data=0.6.3
  - tk=8.6.14
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing_extensions=4.14.0
  - tzdata=2025b
  - unicodedata2=15.1.0
  - urllib3=2.3.0
  - wcwidth=0.2.13
  - wheel=0.45.1
  - wrapt=1.17.0
  - xarray=2025.4.0
  - xarray-einstats=0.9.0
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-renderutil=0.3.10
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.22.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - absl-py==2.3.0
      - alembic==1.16.1
      - annotated-types==0.7.0
      - anyio==4.9.0
      - astunparse==1.6.3
      - bayesdesign==0.5.0
      - blinker==1.9.0
      - cachetools==5.5.2
      - camb==1.6.0
      - click==8.2.1
      - cloudpickle==3.1.1
      - cosmopower-jax==0.5.5
      - databricks-sdk==0.56.0
      - docker==7.1.0
      - fastapi==0.115.12
      - flask==3.1.1
      - flatbuffers==25.2.10
      - gast==0.6.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-auth==2.40.3
      - google-pasta==0.2.0
      - graphene==3.4.3
      - graphql-core==3.2.6
      - graphql-relay==3.2.0
      - greenlet==3.2.3
      - grpcio==1.72.1
      - gunicorn==23.0.0
      - h11==0.16.0
      - itsdangerous==2.2.0
      - jax==0.6.1
      - jaxlib==0.6.1
      - joblib==1.5.1
      - keras==3.10.0
      - libclang==18.1.1
      - mako==1.3.10
      - markdown==3.8
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - ml-dtypes==0.5.1
      - mlflow==2.22.0
      - mlflow-skinny==2.22.0
      - namex==0.1.0
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvcc-cu12==12.5.82
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.5.82
      - nvidia-nvtx-cu12==12.1.105
      - opentelemetry-sdk==1.34.0
      - opentelemetry-semantic-conventions==0.55b0
      - optree==0.16.0
      - packaging==24.2
      - protobuf==5.29.5
      - pyarrow==19.0.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.11.5
      - pydantic-core==2.33.2
      - rich==14.0.0
      - rsa==4.9.1
      - scikit-learn==1.6.1
      - smmap==5.0.2
      - sniffio==1.3.1
      - sqlalchemy==2.0.41
      - sqlparse==0.5.3
      - starlette==0.46.2
      - sympy==1.13.1
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.19.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - torch==2.5.1+cu121
      - torchaudio==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - triton==3.1.0
      - typing-inspection==0.4.1
      - uvicorn==0.34.3
      - werkzeug==3.1.3
      - zuko==1.4.1
prefix: /home/ashandonay/miniconda3/envs/new_bed_py311
