name: bed-cosmo-env
channels:
  - pytorch
  - defaults
  - nvidia
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=2.3.0
  - aom=3.6.1
  - astunparse=1.6.3
  - blas=1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.4.26
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2025.4.26
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - cpython=3.11.13
  - cuda-crt-tools=12.9.86
  - cuda-cudart=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-nvcc-tools=12.9.86
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-nvvm-tools=12.9.86
  - cuda-opencl=12.9.19
  - cuda-runtime=12.4.1
  - cuda-version=12.9
  - cudnn=9.3.0.75
  - ffmpeg=4.4.2
  - filelock=3.18.0
  - flatbuffers=24.3.25
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.13.3
  - gast=0.6.0
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.7.9
  - google-pasta=0.2.0
  - grpcio=1.65.5
  - h2=4.2.0
  - h5py=3.13.0
  - hdf5=1.14.6
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.7.0
  - intel-openmp=2022.0.1
  - jinja2=3.1.6
  - keras=3.10.0
  - keyutils=1.6.1
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.17
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.3
  - libasprintf=0.24.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=12.4.5.8
  - libcufft=11.2.1.3
  - libcufile=1.14.1.1
  - libcurand=10.3.10.19
  - libcurl=8.14.1
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libdeflate=1.24
  - libdrm=2.4.124
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libexpat=2.7.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgettextpo=0.24.1
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libgl=1.7.0
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.1.0
  - libgrpc=1.65.5
  - libiconv=1.18
  - libidn2=2.3.8
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libnghttp2=1.64.0
  - libnpp=12.2.5.30
  - libnsl=2.0.1
  - libnvfatbin=12.9.82
  - libnvjitlink=12.4.127
  - libnvjpeg=12.3.1.117
  - libpciaccess=0.18
  - libpng=1.6.47
  - libprotobuf=5.27.5
  - libre2-11=2024.07.02
  - libsqlite=3.50.0
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libtasn1=4.20.0
  - libtiff=4.7.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libva=2.22.0
  - libvpx=1.13.1
  - libwebp=1.5.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.13.8
  - libzlib=1.3.1
  - llvm-openmp=15.0.7
  - markdown=3.8
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - mdurl=0.1.2
  - mkl=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - namex=0.1.0
  - nccl=2.27.3.1
  - ncurses=6.5
  - nettle=3.9.1
  - networkx=3.5
  - numpy=1.26.4
  - ocl-icd=2.3.3
  - opencl-headers=2024.10.24
  - openh264=2.3.1
  - openjpeg=2.5.3
  - openssl=3.5.0
  - opt_einsum=3.4.0
  - optree=0.16.0
  - p11-kit=0.24.1
  - pillow=11.2.1
  - pip=25.1.1
  - protobuf=5.27.5
  - pthread-stubs=0.4
  - pycparser=2.22
  - pygments=2.19.1
  - pysocks=1.7.1
  - python=3.11.13
  - python-flatbuffers=25.2.10
  - python_abi=3.11
  - pytorch=2.5.1
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - re2=2024.07.02
  - readline=8.2
  - requests=2.32.3
  - rich=14.0.0
  - setuptools=80.9.0
  - six=1.17.0
  - snappy=1.2.1
  - svt-av1=1.4.1
  - tensorboard=2.17.1
  - tensorboard-data-server=0.7.0
  - tensorflow=2.17.0
  - tensorflow-base=2.17.0
  - tensorflow-estimator=2.17.0
  - termcolor=3.1.0
  - tk=8.6.13
  - torchaudio=2.5.1
  - torchtriton=3.1.0
  - torchvision=0.20.1
  - typing-extensions=4.14.0
  - typing_extensions=4.14.0
  - urllib3=2.4.0
  - wayland=1.23.1
  - wayland-protocols=1.44
  - werkzeug=3.1.3
  - wheel=0.45.1
  - wrapt=1.17.2
  - x264=1!164.3095
  - x265=3.5
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - yaml=0.2.5
  - zipp=3.22.0
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - alembic==1.16.1
      - annotated-types==0.7.0
      - anyio==4.9.0
      - astropy==7.1.0
      - astropy-iers-data==0.2025.6.2.0.38.23
      - asttokens==3.0.0
      - bayesdesign==0.5.0
      - blinker==1.9.0
      - cachetools==5.5.2
      - camb==1.6.0
      - click==8.2.1
      - cloudpickle==3.1.1
      - comm==0.2.2
      - contourpy==1.3.2
      - cosmopower-jax==0.5.5
      - cycler==0.12.1
      - databricks-sdk==0.56.0
      - debugpy==1.8.14
      - decorator==5.2.1
      - docker==7.1.0
      - executing==2.2.0
      - fastapi==0.115.12
      - flask==3.1.1
      - fonttools==4.58.1
      - fsspec==2025.5.1
      - getdist==1.6.4
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-auth==2.40.3
      - graphene==3.4.3
      - graphql-core==3.2.6
      - graphql-relay==3.2.0
      - greenlet==3.2.3
      - gunicorn==23.0.0
      - h11==0.16.0
      - ipykernel==6.29.5
      - ipython==9.3.0
      - ipython-pygments-lexers==1.1.1
      - itsdangerous==2.2.0
      - jax==0.6.1
      - jaxlib==0.6.1
      - jedi==0.19.2
      - joblib==1.5.1
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - kiwisolver==1.4.8
      - mako==1.3.10
      - matplotlib==3.10.3
      - matplotlib-inline==0.1.7
      - ml-dtypes==0.5.1
      - mlflow==2.22.1
      - mlflow-skinny==2.22.1
      - nest-asyncio==1.6.0
      - opentelemetry-api==1.34.0
      - opentelemetry-sdk==1.34.0
      - opentelemetry-semantic-conventions==0.55b0
      - packaging==24.2
      - pandas==2.2.3
      - parso==0.8.4
      - pexpect==4.9.0
      - platformdirs==4.3.8
      - prompt-toolkit==3.0.51
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==19.0.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.11.5
      - pydantic-core==2.33.2
      - pyerfa==2.0.1.5
      - pyparsing==3.2.3
      - pyro-api==0.1.2
      - pyro-ppl==1.9.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyzmq==26.4.0
      - rsa==4.9.1
      - scikit-learn==1.7.0
      - scipy==1.15.3
      - smmap==5.0.2
      - sniffio==1.3.1
      - sqlalchemy==2.0.41
      - sqlparse==0.5.3
      - stack-data==0.6.3
      - starlette==0.46.2
      - sympy==1.13.1
      - threadpoolctl==3.6.0
      - tornado==6.5.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - uvicorn==0.34.3
      - wcwidth==0.2.13
      - zuko==1.4.1
prefix: /global/homes/a/ashandon/.conda/envs/bed-cosmo-env
