name: bedcosmo
channels:
  - pytorch
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - absl-py=2.3.0=pyhd8ed1ab_0
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.12.12=py310h89163eb_0
  - aiosignal=1.3.2=pyhd8ed1ab_0
  - aom=3.6.1=h59595ed_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - astunparse=1.6.3=pyhd8ed1ab_3
  - async-timeout=5.0.1=pyhd8ed1ab_1
  - attrs=25.3.0=pyh71513ae_0
  - blas=1.0=mkl
  - blinker=1.9.0=pyhff2d567_0
  - brotli-python=1.1.0=py310hf71b8c6_3
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=5.5.2=pyhd8ed1ab_0
  - certifi=2025.4.26=pyhd8ed1ab_0
  - cffi=1.17.1=py310h8deb56e_0
  - charset-normalizer=3.4.2=pyhd8ed1ab_0
  - click=8.2.1=pyh707e725_0
  - comm=0.2.2=pyhd8ed1ab_1
  - cpython=3.10.18=py310hd8ed1ab_0
  - cryptography=45.0.4=py310h6c63255_0
  - cuda-cccl=12.4.127=0
  - cuda-command-line-tools=11.8.0=0
  - cuda-compiler=12.6.2=0
  - cuda-cudart=11.8.89=0
  - cuda-cudart-dev=11.8.89=0
  - cuda-cuobjdump=12.4.127=0
  - cuda-cupti=11.8.87=0
  - cuda-cuxxfilt=12.4.127=0
  - cuda-documentation=12.4.127=0
  - cuda-driver-dev=12.4.127=0
  - cuda-gdb=12.4.127=0
  - cuda-libraries=11.8.0=0
  - cuda-libraries-dev=12.6.0=0
  - cuda-memcheck=11.8.86=0
  - cuda-nsight=12.4.127=0
  - cuda-nvcc=12.4.131=0
  - cuda-nvdisasm=12.4.127=0
  - cuda-nvml-dev=12.4.127=0
  - cuda-nvprof=12.4.127=0
  - cuda-nvprune=12.4.127=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvrtc-dev=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-nvvp=12.4.127=0
  - cuda-opencl=12.4.127=0
  - cuda-opencl-dev=12.4.127=0
  - cuda-profiler-api=12.4.127=0
  - cuda-runtime=11.8.0=0
  - cuda-sanitizer-api=12.4.127=0
  - cuda-toolkit=11.8.0=0
  - cuda-tools=11.8.0=0
  - cuda-version=11.8=h70ddcb2_3
  - cuda-visual-tools=12.6.0=0
  - cudatoolkit=11.8.0=h4ba93d1_13
  - cudnn=8.9.7.29=hbc23b4c_3
  - debugpy=1.8.14=py310hf71b8c6_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - ffmpeg=4.4.2=gpl_hdf48244_113
  - flatbuffers=23.5.26=h59595ed_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.13.3=ha770c72_1
  - frozenlist=1.6.0=py310h0a1d07c_0
  - gast=0.6.0=pyhd8ed1ab_0
  - gds-tools=1.9.1.3=0
  - giflib=5.2.2=hd590300_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py310he8512ff_0
  - gnutls=3.7.9=hb077bed_0
  - google-auth=2.40.3=pyhd8ed1ab_0
  - google-auth-oauthlib=1.0.0=pyhd8ed1ab_1
  - google-pasta=0.2.0=pyhd8ed1ab_2
  - grpcio=1.54.3=py310heca2aa9_0
  - h2=4.2.0=pyhd8ed1ab_0
  - h5py=3.14.0=nompi_py310hea1e86d_100
  - hdf5=1.14.6=nompi_h2d575fe_101
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.2=h59595ed_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-openmp=2022.0.1=h06a4308_3633
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.37.0=pyh8f84b5b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lapack=3.6.1=ha44fe06_2
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - lerc=4.0.0=h0aef613_1
  - libabseil=20230125.3=cxx17_h59595ed_0
  - libaec=1.1.3=h59595ed_0
  - libasprintf=0.24.1=h8e693c7_0
  - libblas=3.9.0=16_linux64_mkl
  - libcblas=3.9.0=16_linux64_mkl
  - libcublas=11.11.3.6=0
  - libcublas-dev=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufft-dev=10.9.0.58=0
  - libcufile=1.9.1.3=0
  - libcufile-dev=1.9.1.3=0
  - libcurand=10.3.5.147=0
  - libcurand-dev=10.3.5.147=0
  - libcurl=8.14.1=h332b0f4_0
  - libcusolver=11.4.1.48=0
  - libcusolver-dev=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libcusparse-dev=11.7.5.86=0
  - libdeflate=1.24=h86f0d12_0
  - libdrm=2.4.124=hb9d3cd8_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=15.1.0=h767d61c_2
  - libgcc-ng=15.1.0=h69a702a_2
  - libgettextpo=0.24.1=h5888daf_0
  - libgfortran=3.0.0=1
  - libgfortran5=14.1.0=hc5f4f2c_0
  - libgl=1.7.0=ha4b6fd6_2
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.1.0=h767d61c_2
  - libgrpc=1.54.3=hb20ce57_0
  - libiconv=1.18=h4ce23a2_1
  - libidn2=2.3.8=ha4ef2c3_0
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=16_linux64_mkl
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnghttp2=1.64.0=h161d5f1_0
  - libnpp=11.8.0.86=0
  - libnpp-dev=11.8.0.86=0
  - libnsl=2.0.1=hd590300_0
  - libnvfatbin=12.4.127=0
  - libnvfatbin-dev=12.4.127=0
  - libnvjitlink=12.4.127=0
  - libnvjitlink-dev=12.4.127=0
  - libnvjpeg=11.9.0.86=0
  - libnvjpeg-dev=11.9.0.86=0
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.47=h943b412_0
  - libprotobuf=3.21.12=hfc55251_2
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.50.1=hee588c1_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_2
  - libstdcxx-ng=15.1.0=h4852527_2
  - libtasn1=4.20.0=hb9d3cd8_0
  - libtiff=4.7.0=hf01ce69_5
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.22.0=h4f16b4b_2
  - libvpx=1.13.1=h59595ed_0
  - libwebp=1.5.0=hae8dbeb_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.7=h4c95cb1_3
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=15.0.7=h0cdce71_0
  - markdown=3.8=pyhd8ed1ab_0
  - markupsafe=3.0.2=py310h89163eb_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mkl=2022.1.0=hc2b9512_224
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - multidict=6.4.4=py310h89163eb_0
  - nccl=2.27.3.1=h03a54cd_0
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nettle=3.9.1=h7ab15ed_0
  - networkx=3.4=pyhd8ed1ab_0
  - nsight-compute=2024.1.1.4=0
  - oauthlib=3.2.2=pyhd8ed1ab_1
  - openh264=2.3.1=hcb278e6_2
  - openjpeg=2.5.3=h5fbd93e_0
  - openssl=3.5.0=h7b32b05_1
  - opt_einsum=3.4.0=pyhd8ed1ab_1
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.2.1=py310h7e6dc6c_0
  - pip=25.1.1=pyh8b19718_0
  - platformdirs=4.3.8=pyhe01879c_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - propcache=0.3.1=py310h89163eb_0
  - psutil=7.0.0=py310ha75aee5_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyasn1=0.6.1=pyhd8ed1ab_2
  - pyasn1-modules=0.4.2=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - pyjwt=2.10.1=pyhd8ed1ab_0
  - pyopenssl=25.1.0=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.18=hd6af730_0_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-flatbuffers=25.2.10=pyhbc23db3_0
  - python_abi=3.10=7_cp310
  - pytorch=2.5.1=py3.10_cuda11.8_cudnn9.1.0_0
  - pytorch-cuda=11.8=h7e8668a_6
  - pytorch-mutex=1.0=cuda
  - pyu2f=0.1.5=pyhd8ed1ab_1
  - pyyaml=6.0.2=py310h89163eb_2
  - pyzmq=26.4.0=py310h71f11fc_0
  - re2=2023.03.02=h8c504da_0
  - readline=8.2=h8c095d6_2
  - requests=2.32.4=pyhd8ed1ab_0
  - requests-oauthlib=2.0.0=pyhd8ed1ab_1
  - rsa=4.9.1=pyhd8ed1ab_0
  - six=1.17.0=pyhd8ed1ab_0
  - snappy=1.1.10=hdb0a2a9_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - svt-av1=1.4.1=hcb278e6_0
  - tensorboard=2.14.1=pyhd8ed1ab_0
  - tensorboard-data-server=0.7.0=py310h6c63255_2
  - tensorflow=2.14.0=cuda118py310h148f8e3_0
  - tensorflow-base=2.14.0=cuda118py310h2e5981e_0
  - tensorflow-estimator=2.14.0=cuda118py310ha99e61b_0
  - tensorflow-gpu=2.14.0=cuda118py310h0240f8b_0
  - termcolor=3.1.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_hd72426e_102
  - torchaudio=2.5.1=py310_cu118
  - torchtriton=3.1.0=py310
  - torchvision=0.20.1=py310_cu118
  - tornado=6.5.1=py310ha75aee5_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.14.0=h32cad80_0
  - typing_extensions=4.14.0=pyhe01879c_0
  - urllib3=2.4.0=pyhd8ed1ab_0
  - wayland=1.23.1=h3e06ad9_1
  - wayland-protocols=1.45=hd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - wrapt=1.14.1=py310h5764c6d_1
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h7f98852_2
  - yarl=1.20.1=py310h89163eb_0
  - zeromq=4.3.5=h3b0a872_7
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.23.0=py310ha75aee5_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - alembic==1.16.1
      - annotated-types==0.7.0
      - anyio==4.9.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - astropy==6.1.7
      - astropy-iers-data==0.2025.6.9.14.9.37
      - async-lru==2.1.0
      - babel==2.18.0
      - bayesdesign==0.5.0
      - bayesflow==2.0.7
      - beautifulsoup4==4.14.3
      - bed-cosmo==0.1.0
      - bedcosmo==0.1.0
      - black==26.1.0
      - bleach==6.3.0
      - cfgv==3.5.0
      - clipy-like==0.11
      - cloudpickle==3.1.1
      - cobaya==3.5.7
      - contourpy==1.3.2
      - cosmopower-jax==0.5.5
      - cosmoprimo==1.0.0
      - coverage==7.13.1
      - cycler==0.12.1
      - databricks-sdk==0.57.0
      - defusedxml==0.7.1
      - desilike==0.0.1
      - dill==0.4.0
      - distlib==0.4.0
      - docker==7.1.0
      - fastapi==0.115.12
      - fastjsonschema==2.21.2
      - filelock==3.20.3
      - flask==3.1.1
      - flask-cors==6.0.1
      - fonttools==4.58.4
      - fqdn==1.5.1
      - fsspec==2025.5.1
      - future==1.0.0
      - fuzzywuzzy==0.18.0
      - galsim==2.7.2
      - getdist==1.6.4
      - gitdb==4.0.12
      - gitpython==3.1.44
      - graphene==3.4.3
      - graphql-core==3.2.6
      - graphql-relay==3.2.0
      - greenlet==3.2.3
      - gunicorn==23.0.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huey==2.5.5
      - identify==2.6.16
      - iniconfig==2.3.0
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jax==0.6.2
      - jax-cuda12-pjrt==0.6.2
      - jax-cuda12-plugin==0.6.2
      - jaxlib==0.6.2
      - joblib==1.5.1
      - json5==0.13.0
      - jsonpointer==3.0.0
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-console==6.6.3
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.4
      - jupyterlab==4.5.3
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.16
      - keras==3.12.0
      - kiwisolver==1.4.8
      - lark==1.3.1
      - librt==0.7.8
      - lsstdesc-coord==1.3.0
      - mako==1.3.10
      - markdown-it-py==4.0.0
      - matplotlib==3.10.3
      - mdurl==0.1.2
      - mistune==3.2.0
      - ml-dtypes==0.5.4
      - mlflow==3.7.0
      - mlflow-skinny==3.7.0
      - mlflow-tracing==3.7.0
      - mpi4py==4.1.1
      - mypy==1.19.1
      - mypy-extensions==1.1.0
      - namex==0.1.0
      - nbclient==0.10.4
      - nbconvert==7.17.0
      - nbformat==5.10.4
      - nodeenv==1.10.0
      - notebook==7.5.3
      - notebook-shim==0.2.4
      - numpy==1.26.4
      - opentelemetry-api==1.34.1
      - opentelemetry-proto==1.39.1
      - opentelemetry-sdk==1.34.1
      - opentelemetry-semantic-conventions==0.55b1
      - optree==0.18.0
      - overrides==7.7.0
      - pandas==2.3.0
      - pandocfilters==1.5.1
      - pathspec==1.0.4
      - pluggy==1.6.0
      - portalocker==3.1.1
      - pre-commit==4.5.1
      - prometheus-client==0.24.1
      - protobuf==6.33.2
      - py-bobyqa==1.5.0
      - pyarrow==20.0.0
      - pybind11==3.0.1
      - pydantic==2.11.6
      - pydantic-core==2.33.2
      - pyerfa==2.0.1.5
      - pyparsing==3.2.3
      - pyro-api==0.1.2
      - pyro-ppl==1.9.1
      - pytest==9.0.2
      - pytest-cov==7.0.0
      - pytest-mock==3.15.1
      - python-dotenv==1.2.1
      - python-json-logger==4.0.0
      - pytokens==0.4.1
      - pytz==2025.2
      - referencing==0.37.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==14.2.0
      - rpds-py==0.30.0
      - ruff==0.15.0
      - scikit-learn==1.7.0
      - scipy==1.15.3
      - seaborn==0.13.2
      - send2trash==2.1.0
      - setuptools==71.1.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.8.3
      - speclite==0.20
      - sqlalchemy==2.0.41
      - sqlparse==0.5.3
      - starlette==0.46.2
      - sympy==1.13.1
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - tomli==2.2.1
      - tqdm==4.67.1
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - uri-template==1.3.0
      - uvicorn==0.34.3
      - virtualenv==20.36.1
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - widgetsnbextension==4.0.15
      - zuko==1.4.1
prefix: /home/ashandonay/miniconda3/envs/bedcosmo
